// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PresidentsExcercise.Model;
using System;

namespace PresidentsExcercise.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PresidentsExcercise.Model.President", b =>
                {
                    b.Property<int>("PresidentID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("Birthday");

                    b.Property<string>("Birthplace")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("Deathday");

                    b.Property<string>("Deathplace")
                        .HasMaxLength(100);

                    b.Property<string>("Fullname")
                        .HasColumnName("President")
                        .HasMaxLength(100);

                    b.HasKey("PresidentID");

                    b.ToTable("Presidents","Exercise");
                });
#pragma warning restore 612, 618
        }
    }
}
